# Numpy


In [1]:
#1
import numpy as np

In [2]:
#2
print(np.__version__)
print(np.__spec__)

1.26.4
ModuleSpec(name='numpy', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000019ACFEACED0>, origin='c:\\Users\\heman\\.conda\\envs\\notebook\\Lib\\site-packages\\numpy\\__init__.py', submodule_search_locations=['c:\\Users\\heman\\.conda\\envs\\notebook\\Lib\\site-packages\\numpy'])


In [3]:
#3
a = np.zeros(20)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4
b = np.zeros(10)
b[4]=1
print(b)
c= (np.arange(10)==4).astype(int)
print(c)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]


In [5]:
#5
d = np.arange(10,50) #First inclusive last exclusive
print(d)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#6
e = np.flip(d)
e

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
#7
f = np.zeros(shape=(4,3))
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#8
z = np.array( [1,2,0,0,4,0])

np.where(z == 0)

(array([2, 3, 5], dtype=int64),)

In [11]:
#9
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#10
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.15205437 0.32716415 0.13378848]
  [0.97249945 0.45942794 0.82045324]
  [0.34695048 0.67101626 0.28155655]]

 [[0.4093551  0.02523991 0.59717281]
  [0.21962683 0.92258412 0.2568343 ]
  [0.18995601 0.7854235  0.36164223]]

 [[0.26217498 0.84942831 0.54376264]
  [0.4249035  0.4324498  0.49049657]
  [0.7067488  0.67124526 0.5487271 ]]]


In [16]:
#11
arr = np.random.rand(10, 10)
min_value = np.min(arr)
max_value = np.max(arr)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 0.004315765567726837
Maximum Value: 0.9802710613268646


In [17]:
#12
v = np.random.rand(30)
mean_value = np.mean(v)
print("Mean Value:", mean_value)

Mean Value: 0.45563708616825505


In [18]:
#13
b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
#14
c = np.zeros((8, 8))
c[::2, ::2] = 1
c[1::2, 1::2] = 1
print(c)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [20]:
#15
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
product_matrix = np.dot(a, b)
print(product_matrix)


[[0.22966324 0.14495969]
 [0.62038062 0.912657  ]
 [0.35950096 0.59613863]
 [0.28694829 0.34671395]
 [0.36846366 0.64118044]]


In [21]:
#16
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x[(x >= 3) & (x <= 8)] *= -1
print(x)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [22]:
#17
z = np.random.rand(10)
z = np.sort(z)
print(z)

[0.0110932  0.02816647 0.47970287 0.5008804  0.55705401 0.62932559
 0.74202012 0.8460591  0.86736109 0.9019428 ]


In [25]:
#18
q = np.random.rand(10)
print(q)
max_index = np.argmax(q)
q[max_index] = 0
print(q)

[0.68333348 0.10165937 0.00947672 0.61906798 0.83063092 0.11004819
 0.50926239 0.56824317 0.02198684 0.80687878]
[0.68333348 0.10165937 0.00947672 0.61906798 0.         0.11004819
 0.50926239 0.56824317 0.02198684 0.80687878]


In [26]:
#19
prices = np.array([6999, 7500, 11999, 27899, 14999, 9999])

In [28]:
prices = prices.astype(float)
print(prices)

[ 6999.  7500. 11999. 27899. 14999.  9999.]


In [29]:
prices = np.append(prices, 13999)
print(prices)


[ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


In [30]:
prices = np.flip(prices)
print(prices)


[13999.  9999. 14999. 27899. 11999.  7500.  6999.]


In [31]:
gst_rate = 0.18
prices = prices * (1 + gst_rate)

print(prices)

[16518.82 11798.82 17698.82 32920.82 14158.82  8850.    8258.82]


In [32]:
prices = np.sort(prices)[::-1]
print(prices)

[32920.82 17698.82 16518.82 14158.82 11798.82  8850.    8258.82]


In [33]:
average_price = np.mean(prices)
print("Average Price:", average_price)


Average Price: 15743.560000000001


In [34]:
price_diff = np.max(prices) - np.min(prices)
print("Price Difference:", price_diff)

Price Difference: 24662.0
