In [7]:

import torch as t
device = "cuda" if t.cuda.is_available() else "cpu"

In [3]:
x = t.empty(4)
x

tensor([1.7023e+38, 1.7881e-42, 0.0000e+00, 0.0000e+00])

In [4]:
y = t.empty(2,3)
y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
my_tensor = t.tensor([[1,2,3],[4,5,6]],device=device,dtype=t.float32)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
cpu
torch.Size([2, 3])


In [18]:
d = t.zeros(3,3)
print(d)
d1 = t.zeros(size=(2,3))
print(d1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
c = t.rand(4,6)
c

tensor([[0.7138, 0.1525, 0.9629, 0.5530, 0.4537, 0.6500],
        [0.1940, 0.1711, 0.0054, 0.8682, 0.3660, 0.3748],
        [0.4094, 0.0789, 0.9249, 0.2347, 0.2580, 0.2208],
        [0.6182, 0.5288, 0.0376, 0.9590, 0.6029, 0.9211]])

In [22]:
g = t.ones(5,3)
g

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
o = t.eye(3,3)
o

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [29]:
arr= t.arange(1,10,3)
print(arr)

arr1 = t.arange(start=10,end=100,step=4)
arr1

tensor([1, 4, 7])


tensor([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74, 78,
        82, 86, 90, 94, 98])

In [38]:
abc = t.linspace(0.1,1,10)
print(abc)
abc = t.linspace(start=0.1,end=1,step=10,)
abc

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


TypeError: linspace() received an invalid combination of arguments - got (step=int, start=float, end=int, ), but expected one of:
 * (Tensor start, Tensor end, int steps, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Tensor end, int steps, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Tensor start, Number end, int steps, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, int steps, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
